### ISSUE TITLE
Update the documentation with the test functionality

### ISSUE THREAD

**Issue by scalabrindario** [scalabrindario/Covid-19#14]
@LucaBallistri updates the `README.me` file according with the last changes happened for the test functionality

**Comment by LucaBallistri** [comment]
Added here: https://github.com/scalabrindario/Covid-19/commit/ccb824a39e326550cf11fd302a67e949b978d62c
I have made a mistake during the process, so I have fixed it here: https://github.com/scalabrindario/Covid-19/commit/0b0fb6882f1dfc58fbb8f92fdf1a3b3cf36616c9
