### ISSUE TITLE
PEP8 compliances

### ISSUE THREAD

**Issue by scalabrindario** [scalabrindario/Covid-19#15]
I created a branch called `iss_15`. Starting from this, each one of us will create a branch, and fix a file according to PEP8 rules.

- @scalabrindario: file `database.py` --> Branch called **PEP8_database**
- @andreaparisi96: file `main.py` --> Branch called **PEP8_main**
- @LucaBallistri: file `covid19.py` and `test_csv_maker.py`  --> Branch called **PEP8_covid19_test**
- @pietroquerci1999: file `csv_maker.py`  --> Branch called **PEP8_csv_maker**

Please when you finish comment below, next I will merge all

**Comment by LucaBallistri** [comment]
I fixed my files here: https://github.com/scalabrindario/Covid-19/commit/cbb6ebaf7411d11b4a6658e3fb4f6045ed3b4c25 and here: https://github.com/scalabrindario/Covid-19/commit/2907909a709c405d3dea08c9af881c337f72804f

**Comment by pietroquerci1999** [comment]
I fixed my file here: https://github.com/scalabrindario/Covid-19/commit/64a3c48c14215db0e3ea8aea37a070ed17474e7b

**Comment by andreaparisi96** [comment]
I fixed my file here: https://github.com/scalabrindario/Covid-19/commit/fbe88850b5afa3e2d207e4b4b0aa62ead71d5382

**Comment by scalabrindario** [comment]
I merged all the branches here https://github.com/scalabrindario/Covid-19/commit/dcd37060458eb0995b892dedda2d0b812f49be2a
