### ISSUE TITLE
Missing __init__.py

### ISSUE THREAD

**Issue by pietroquerci1999** [scalabrindario/Covid-19#3]
The file `__init__.py` is missing and should be added inside the folder `covid_package`

**Comment by LucaBallistri** [comment]
I added the `__init__.py` file here https://github.com/scalabrindario/Covid-19/commit/ccc7c58a2b9c5eaeb3048410dc22fb745fbb711a

**Comment by LucaBallistri** [comment]
Fixed the kanban board
