### ISSUE TITLE
Fix the documentation

### ISSUE THREAD

**Issue by scalabrindario** [scalabrindario/Covid-19#5]
@pietroquerci1999 please fix the `README.me` file. You should fix according the modifications made by @andreaparisi96

**Comment by scalabrindario** [comment]
@pietroquerci1999 please fix the table because the markdown is wrong

**Comment by scalabrindario** [comment]
@LucaBallistri please solve the issue, because we are late

**Comment by LucaBallistri** [comment]
Yes, I just solved here: https://github.com/scalabrindario/Covid-19/commit/bc24bd1b773ec9ad5883b99703dfc83c58a709c3
