### ISSUE TITLE
Implement database

### ISSUE THREAD

**Issue by LucaBallistri** [scalabrindario/Covid-19#7]
Pietro, we need to implement the database as soon as possible

**Comment by pietroquerci1999** [comment]
I have just created the file `database.py` with this commit: https://github.com/scalabrindario/Covid-19/commit/9df6714dc730229b4eaf4fea90ad82b18ee205ce

**Comment by LucaBallistri** [comment]
Implemented the database here:  https://github.com/scalabrindario/Covid-19/commit/39e0aef4140983ef729d4134cdc8981e3c0a5e0f
